version: "3.9" 
services:
  products-api:
    container_name: supermarket_products-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      GIN_MODE: release
      PORT: 3001
      MYSQL_URI: "root:root@tcp(mysql:3306)/supermarket_products?charset=utf8mb4&parseTime=True&loc=Local"
      ACCOUNT_API_URL: http://supermarket_accounts-api:3000/api/v1
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
  mysql:
    container_name: supermarket_products-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supermarket_products
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
networks:
  default:
    name: supermarket
