version: "3.9" 
services:
  accounts-api:
    container_name: "supermarket_accounts-api" 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      GIN_MODE: release
      PORT: 3000
      MYSQL_URI: "root:root@tcp(mysql:3306)/supermarket_accounts?charset=utf8mb4&parseTime=True&loc=Local"
      JWT_SECRET: 6014n6_5u93rm4k37
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
  mysql:
    container_name: supermarket_accounts-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supermarket_accounts
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - accounts_data:/var/lib/mysql
volumes:
  accounts_data: 
networks:
  default:
    name: supermarket